apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  labels:
    component: dwse-celery-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      component: dwse-celery-worker
  template:
    metadata:
      labels:
        component: dwse-celery-worker
    spec:
      containers:
      - name: celery-worker
        image: your-docker-username/dwse-celery-worker:latest
        env:
        - name: BROKER_URL
          value: "redis://redis:6379/0"
        - name: RESULT_BACKEND
          value: "redis://redis:6379/0"
        command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: celery-worker-service
spec:
  selector:
    component: dwse-celery-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
